#!/bin/sh

#~ echo Running.

cd ~/'bin/bak_files/to_archive' || exit "${?}"
zip -r -FS --quiet '../stuff.zip' *
printf '~/bin/bak: zip: code %s\n' "${?}" 

#~ ~/'Dev/drafts-and-stuff/Python/pyautogui/upload.py'

#~ echo Done.
