#!/bin/bash

# Set your battery device path (find with: upower -e)
BATTERY="/org/freedesktop/UPower/devices/battery_BAT1"
LOW_LEVEL=20
CRITICAL_LEVEL=10

while true; do
  STATE=$(upower -i $BATTERY | grep "state:" | awk '{print $2}')
  PERCENT=$(upower -i $BATTERY | grep "percentage:" | awk '{print $2}' | sed 's/%//')

  if [ "$STATE" = "discharging" ]; then
    if [ "$PERCENT" -le "$CRITICAL_LEVEL" ]; then
      notify-send -u critical "Battery Critically Low" "Battery level is at ${PERCENT}%! [~/bin/battery_notification]"
    elif [ "$PERCENT" -le "$LOW_LEVEL" ]; then
      notify-send -u normal "Battery Low" "Battery level is at ${PERCENT}%. [~/bin/battery_notification]"
    fi
  fi
  sleep 60
done
