#!/bin/sh

# dir_not_empty [DIRECTORY]...
# Check that if each argument is the path of a nonempty directory.

_dir_not_empty()
{
	[ -d "${1}" ] && [ -n "$(ls -A -- "${1}")" ]
}

parse_options='true'
result='true'
while [ "${#}" -gt 0 ]
do
    if "${parse_options}"; then
        case "${1}" in
            (-h|--help)
                printf '%s\n' 'Usage:   dir_not_empty [DIRECTORY]...' 'Purpose: check that each argument is the path of a nonempty directory.' >&2
                exit 2
                ;;
            (--)
            # end of options
                shift
                parse_options='false'
                continue
                ;;
        esac
    fi
    if _dir_not_empty "${1}"; then
        shift
    else
        result='false'
        break
    fi
done

"${result}"
