#!/usr/bin/env sh

default_ext='mp4'
max_attempts=100    # maximal number of attempts to find an available file name (set at 0 to use no limit)

while true
do
    echo 'Title:'
    read title

    echo 'URL:'
    read url

    printf "Extension [${default_ext}]: "
    # (type a hyphen if you want no extension)
    read ext

    if [ -n "${title}" ]
    then
        title="$(tr '/' '-' <<-EOF
			${title}
			EOF
		)"
    else
        title="$(~/bin/new_rand)"
    fi

    case "${ext}" in
        ('')
            ext=".${default_ext}"
            ;;
        (-)
            ext=''
            ;;
        (.*)
            ;;
        (*)
            ext=".${ext}"
            ;;
    esac

    dest="${title}${ext}"

    if [ -e "${dest}" ]
    then
        echo "Filename already taken: “${dest}”"
        original_dest="${dest}"
        title="${title}_"
        i=1
        available=true
        while [ -e "${dest}" ]
        do
            if [ "${i}" -gt "${max_attempts}" ]
            then
                printf 'Using that name anyway.\n'
                dest="${original_dest}"
                available=false
                break
            fi
            title="${title}$(~/bin/new_rand)"
            dest="${title}${ext}"
            let 'i++'
        done
        "${available}" && printf 'Using a different filename.\n'
    fi

    printf 'Target: %s\n' "${dest}"
    echo 'OK? [enter|ctrl-c]'
    read answer

    if ! curl \
        -L \
        --continue-at - \
        --output "${dest}" \
        "${url}"
    then
        echo "curl returned error code ‘${?}’." >&2
        exit 3
    fi
done
