#!/usr/bin/env sh

default_ext='mp4'

echo 'Title:'
read title

echo 'URL:'
read url

printf "Extension [${default_ext}]: "
read ext
# (type a hyphen if you want no extension)

title="$(tr '/' '-' <<-EOF
	${title}
	EOF
)"

case "${ext}" in
    ('')
        ext="${default_ext}"
        ;;
    (-)
        ext=''
        ;;
esac

dest="${title}${ext:+.${ext}}"

printf 'Target: %s\n' "${dest}"
echo 'OK? [enter|ctrl-c]'
read answer

if [ -e "${dest}" ]; then
    printf 'destination already exists: “%s”\n' "${dest}"
    exit 2
fi

if ! curl \
    -L \
    --continue-at - \
    --output "${dest}" \
    "${url}"
then
    echo "curl returned error code ‘${?}’." >&2
    exit 3
fi
