#!/bin/sh

# ./pick_line [file]
# print a pseudo-random line from $file

if [ -z "${1}" ]
then
    file=~/'bin/pick_line_list3'
elif [ -f "${1}" ]
then
    file="${1}"
else
    printf 'bad usage: argument should be a file or left empty. (Value: “ %s ”)\n' "${1}"
    exit 2
fi

printf '(picking from %s)\n' "${file}"

count="$(wc -l <"${file}")"

line="$(~/bin/new_rand 1 "$((count+1))")"
awk "NR==${line}{print;exit}" "${file}"
