#!/bin/bash

# press_key_later [duration [time_unit [key]]] - wait then press some key (default: wait 40 minutes then press space)


# duration
duration="${1:-40}"

# time unit (see bin/chrono documentation to find valid values)
unit="${2:-m}"

# key to press (see pyautogui documentation to find valid values)
key="${3:-space}"


# Code

error=false
[ "${#}" -ge 4 ] && error=true
case "${1}" in
    (-h|--help) error=true;;
esac

if "${error}"; then
    echo "${0}: Bad usage: you probably should read the source before using that script."
    exit 1
else
    ~/bin/chrono -m "${duration}" "${unit}"
    python -c "import pyautogui;pyautogui.press('${key}')"
fi
