#!/bin/bash

# press_key_later [duration [time_unit [key]]] - wait then press some key (default: wait 40 minutes then press space)


# duration
duration="${1:-40}"

# time unit (see bin/chrono documentation to find valid values)
unit="${2:-m}"

# key to press (see pyautogui documentation to find valid values)
key="${3:-space}"


# Code

case "${1}" in
    (-h|--help)
        printf '%s\n' 'Usage:   press_key_later [duration [time_unit [key]]]' 'Purpose: wait then simulate pressing some key (default: wait 40 minutes then press space).'
        exit 1
        ;;
esac

if [ "${#}" -ge 4 ]; then
    echo "${0}: Bad usage: you probably should read the source before using that script."
    exit 1
else
    ~/bin/chrono -m "${duration}" "${unit}"
    python -c "import pyautogui;pyautogui.press('${key}')"
fi
