#!/bin/sh

# Usage:
# Check the parameters as well as the line marked “EDIT ME”, then run this
# script in the directory of the subtitles to rename.

season=8
first_episode=1
last_episode=8

z='0'
i="${first_episode}"
while [ "${i}" -le "${last_episode}" ]
do
  [ "${i}" -ge 10 ] && z=''
  mv -vi *."S0${season}E${z}${i}".*.srt "Archer S0${season}E${z}${i}.srt"  # EDIT ME
  #~ mv -vi "0${season}.${z}${i} "*.srt "Archer S0${season}E${z}${i}.srt"  # EDIT ME
  let 'i++'
done
