#!/bin/sh

# ./sdn [-f]
# Shut down. With no argument, wait for Firefox to quit.

debug=true

# handle arguments
wait=true
while [ "${#}" -ge 1 ]
do
    case "${1}" in
        -f) wait=false
            shift
            ;;
        *)  echo 'bad usage' >&2
            exit 2
            ;;
done

# wait for Firefox to quit
while "${wait}"
do
    if ps ax | grep -i firefox | grep -v grep; then
        sleep 3
    else
        wait=false
        echo -n 'Firefox does not seem to be running anymore.'
        if "${debug}"; then
            echo -n ' Shut down? [enter|ctrl-c] '
            read ans
        fi
    fi
done

# shut down
shutdown now
