#!/bin/sh

# ./sdn [-f]
# Shut down. With no argument, wait for Firefox to quit.

PROG_NAME='sdn'
debug=true

# handle arguments
wait=true
while [ "${#}" -ge 1 ]
do
    case "${1}" in
        -f) wait=false
            shift
            ;;
        *)  echo "${PROG_NAME}: bad usage" >&2
            exit 2
            ;;
    esac
done

if ~/bin/wait_until_quit -p 12 'firefox'; then
    echo -n "${PROG_NAME}: Firefox does not seem to be running anymore."

    if "${debug}"; then
        echo -n ' Shut down? [enter|ctrl-c] '
        read ans
    fi

    shutdown now
else
    echo "${PROG_NAME}: ‘wait_until_quit’ returned with error ‘${?}’." >&2
fi
