#!/bin/bash
# setDNS <new_profile>
# change profile to /etc/resolvconf.new_profile.conf

newProfile="${1}"
basename='/etc/resolvconf'
ext='conf'
link="${basename}.${ext}"
target="${basename}.${newProfile}.${ext}"

if [ -f "${target}" ]; then
    if sudo ln -vsf "${target}" "${link}"; then
        # update config:
        sudo resolvconf -u || echo "setDNS: error: resolvconf returned code ${?}." >&2
    else
        echo "setDNS: error: ln returned code ${?}." >&2
    fi
else
    if [ "${#}" -ge 1 ]; then
        echo "setDNS: error: not a file: “${target}”" >&2
    fi
    echo -n 'Current profile: '
    readlink "${link}"
    echo 'Profiles available:'
    for file in "${basename}".*."${ext}"
    do
        echo "${file}"
    done
fi
