#!/bin/sh

log_file=~/'tmp/stuff/update.log'

printf '~/bin/update: Delete last log? [n]/y '
read ans
case "${ans}" in
    (y|Y) rm -v "${log_file}" ;;
esac

script -ac ~/bin/_utils/update "${log_file}"
printf '\n' >> "${log_file}"
exec zsh
