#!/bin/sh

echo '### Use xterm to be able to scroll. ###'

echo 'Updating mirror list with reflector.'
sudo reflector --sort score --save /etc/pacman.d/mirrorlist || echo "erreur code ${?} retournée par reflector"

if sudo pacman -Syyu; then
    printf '\n%s\n\n' '~/bin/update: Updating ruby gems.'
    gem update || echo "erreur code ${?} retournée par gem"
else
    echo "erreur code ${?} retournée par pacman"
fi

zsh
