#!/bin/bash

# watcher - launch files with VLC

## parameters

source_dir='/home/val/mnt/Data/Downloads/v/unwatched'
#~ move_to_target_dir=false
move_to_target_dir=true
target_dir='../watched'
print_help_at_launch=true

file_viewer='spacefm'

## code

PROGNAME="watcher"
PROGDIR="$(cd "$(dirname "${0}")" && pwd -P)"

# load libraries
. "${PROGDIR}/_utils/load" || { echo "${PROGNAME}: line ${LINENO}: error code ${?} while sourcing “ ${PROGDIR}/_utils/load ”" >&2 ; exit 1; }

cd "${source_dir}" || { _error "${PROGNAME}: line ${LINENO}: error code ${?} while changing directory"; exit 1; }

# make target dir if necessary
if "${move_to_target_dir}"; then
    mkdir -vp "${target_dir}" || { move_to_target_dir=false ; echo "Problem while creating directory ${target_dir}" >&2 ; }
fi

# debug mode
no_video=false
[ "${#}" -gt 0 ] && no_video=true

"${print_help_at_launch}" && _usage

_question()
{
    printf '“ %s ”. Action ? ' "${file}"
    "${move_to_target_dir}" && printf '[y]/n/' || printf '[n]/'
    printf '%s\n' 'q/r/d/p/h'
}

_play_vid()
{
    if ! "${no_video}"; then
        vlc "${file}" 1>/dev/null 2>&1 & disown
    fi
}

#~ while true
#~ do
# launch up to 20 files
"${PROGDIR}/pick_file" 20 . | while read file
do
    [ -e "${file}" ] || break   # check if user removed file
    dir="$(dirname "${file}")"
    _question
    _play_vid
    reask=true
    while "${reask}"
    do
        read ans < /dev/tty
        case "${ans}" in
            p|P)    # file viewer
                [ -d "${dir}" ] && "${file_viewer}" "${dir}" >/dev/null 2>&1 &
                ;;
            r|R)    # replay
                _play_vid
                ;;
            d|D)    # delete file
                rm -v "${file}"
                reask=false
                ;;
            n|N)    # skip next actions
                reask=false
                ;;
            q|Q)    # exit
                echo 'Quitting.'
                exit 0
                ;;
            y|Y)   # move file
                "${move_to_target_dir}" && mv -v "${file}" "${target_dir}"
                reask=false
                ;;
            '')
                if "${move_to_target_dir}"; then
                    "${move_to_target_dir}" && mv -v "${file}" "${target_dir}"
                fi
                reask=false
                ;;
            *)    # print help
                _usage
                ;;
        esac
        if "${reask}"; then
            _question
        fi
    done
done
