#!/bin/sh
# POSIX

# substring - extract a substring from a string

PROGNAME="substring"
PROGDIR="$(cd "$(dirname "${0}")" && pwd)"
SCRIPTS_ROOT="${HOME}/Documents/Dev/languages/scripting/shell"

# load libraries
. "${SCRIPTS_ROOT}/_utils/load" || { echo "${PROGNAME}: line ${LINENO}: error code ${?} while sourcing “ ${SCRIPTS_ROOT}/_utils/load ”" >&2 ; exit 1; }

if [ "${#}" -eq 0 ] || [ "${1}" = '-h' ] || [ "${1}" = '--help' ]; then
    _usage
    exit 0
fi
[ "${#}" -eq 2 ] || { _usage ; exit 1; }

minuend="${2}"                                      #a=b+c
prefix_to_keep="${1}"                               #b=?	(unknown string matching pattern ${1})
suffix_junk="${minuend#${prefix_to_keep}}"          #c=a-b	(c is now known)
kept="${minuend%%${suffix_junk}}"                   #b=a-c	(we can compute b)

printf "${kept}\n"
