#!/bin/bash

if ! type _math_log 2>/dev/null 1>&2  # include_once _utils/math/functions
then
    [ -n "${SCRIPTS_ROOT}" ]  || SCRIPTS_ROOT='/home/val/Documents/Dev/languages/scripting/shell'
    . "${SCRIPTS_ROOT}/_utils/math/functions"
fi
