#!/bin/sh

printf '\n%s\n\n' '### Use xterm to be able to scroll. ###'

format_string='~/bin/_utils/update: debug: %s\n'

printf "${format_string}" 'Updating mirror list with reflector.'
sudo reflector --sort score --save /etc/pacman.d/mirrorlist || echo "erreur code ${?} retournée par reflector"

printf "${format_string}\n" 'Updating packages with pacman.'
if sudo pacman -Syu --noprogressbar; then
    printf "\n${format_string}\n" 'Updating ruby gems.'
    gem update || echo "erreur code ${?} retournée par gem"
else
    echo "erreur code ${?} retournée par pacman"
fi
printf '\n'
