#!/bin/sh

PROG_NAME='~/bin/_utils/update'

printf '\n%s: info: %s\n\n' "${PROG_NAME}" 'Use xterm to be able to scroll.'

printf "%s: debug: %s\n" "${PROG_NAME}" 'Updating mirror list with reflector.'
sudo reflector --sort score --save /etc/pacman.d/mirrorlist || printf "%s: error: %s\n" "${PROG_NAME}" "reflector returned code ${?}"

printf "%s: debug: %s\n\n" "${PROG_NAME}" 'Updating packages with pacman.'
if sudo pacman -Syu --noprogressbar; then
    printf "\n%s: debug: %s\n\n" "${PROG_NAME}" 'Updating ruby gems.'
    gem update || printf "%s: error: %s\n" "${PROG_NAME}" "gem returned code ${?}"
else
    printf "%s: error: %s\n" "${PROG_NAME}" "pacman returned code ${?}"
fi
