#!/bin/sh

# Please use xterm to be able to scroll.

PROG_NAME='~/bin/_utils/update'

printf "%s: info: %s\n" "${PROG_NAME}" 'Updating mirror list (reflector).'
sudo reflector --sort score --save /etc/pacman.d/mirrorlist || printf "%s: error: %s\n" "${PROG_NAME}" "reflector returned code ${?}"

printf "%s: info: %s\n\n" "${PROG_NAME}" 'Updating packages (pacman).'
if sudo pacman -Syu --noprogressbar; then
    printf "\n%s: info: %s\n\n" "${PROG_NAME}" 'Updating ruby gems.'
    gem update || printf "%s: error: %s\n" "${PROG_NAME}" "gem returned code ${?}"
else
    printf "%s: error: %s\n" "${PROG_NAME}" "pacman returned code ${?}"
fi
