#!/bin/bash

_usage()
{
	str1="\n${SECTION}%s${PLAIN}\n"
	str2=" ${SECTION}%s${PARAM}%s${SECTION}%s"
	str3="  ${PARAM}%s${PLAIN}\n"
	str4="      ${TEXT}%s %s${STRONG}%s${TEXT}%s${PLAIN}\n"
	str5="      ${TEXT}%s${PLAIN}\n"
	printf "\n${TITLE}${PROGNAME}${DESC} - %s${PLAIN}\n"        'select random files in a folder hierarchy'
	printf "${str1}"                                                'Usage:'
	printf "  ${TITLE}%s"                                             "${PROGNAME}"
	printf "${str2}"                                                     '[' 'options' ']'
	printf "${str2}"                                                     '[' 'number_of_files' ']'
	printf "${str2}${PLAIN}\n"                                           '<' 'folder' '>'
	printf "${str1}"                                                'Parameters:'
	printf "${str3}"                                                    'number_of_files'
	printf "${str4}"                                                        'number of files to pick' '(default ' '1' ')'
	printf "${str3}"                                                    'folder'
	printf "${str5}"                                                        'where to select the files'
	printf "${str1}"                                                'Options:'
	printf "${str3}"                                                    '-h, --help'
	printf "${str5}"                                                        'show this help message'
	printf "${str3}"                                                    '-r'
	printf "${str5}\n\n"                                                    'allow repetitions'
}
