#!/bin/bash

_usage()
{
	cat <<-'EOF'

	 Type an action and validate with [enter].

	EOF
	"${move_videos}" && echo "      y: move video to “ ${dir_moved_videos} ”"
	cat <<-'EOF'
	      n: next video
	      q: quit
	      r: replay video
	      d: delete video
	      p: show folder in file browser
	      s: show tags
	      v: show existing values of a tag
	      t: tag
	      u: untag
	      h: print this help

	EOF
}
